OBJ=\
 $(PDPATH)/src/d_ugen.o \
 $(PDPATH)/src/g_rtext.o \
 $(PDPATH)/src/d_arithmetic.o \
 $(PDPATH)/src/x_misc.o \
 $(PDPATH)/src/d_filter.o \
 $(PDPATH)/src/g_array.o \
 $(PDPATH)/src/s_path.o \
 $(PDPATH)/src/m_glob.o \
 $(PDPATH)/src/m_class.o \
 $(PDPATH)/src/x_scalar.o \
 $(PDPATH)/src/s_loader.o \
 $(PDPATH)/src/x_list.o \
 $(PDPATH)/src/d_fft_fftsg.o \
 $(PDPATH)/src/d_dac.o \
 $(PDPATH)/src/m_binbuf.o \
 $(PDPATH)/src/x_net.o \
 $(PDPATH)/src/g_text.o \
 $(PDPATH)/src/g_mycanvas.o \
 $(PDPATH)/src/g_all_guis.o \
 $(PDPATH)/src/s_inter.o \
 $(PDPATH)/src/d_misc.o \
 $(PDPATH)/src/s_audio.o \
 $(PDPATH)/src/d_resample.o \
 $(PDPATH)/src/g_vumeter.o \
 $(PDPATH)/src/d_delay.o \
 $(PDPATH)/src/g_numbox.o \
 $(PDPATH)/src/m_conf.o \
 $(PDPATH)/src/d_math.o \
 $(PDPATH)/src/g_bang.o \
 $(PDPATH)/src/x_acoustics.o \
 $(PDPATH)/src/g_hslider.o \
 $(PDPATH)/src/s_file.o \
 $(PDPATH)/src/d_array.o \
 $(PDPATH)/src/s_audio_paring.o \
 $(PDPATH)/src/g_scalar.o \
 $(PDPATH)/src/x_array.o \
 $(PDPATH)/src/s_utf8.o \
 $(PDPATH)/src/g_hdial.o \
 $(PDPATH)/src/s_audio_pa.o \
 $(PDPATH)/src/g_traversal.o \
 $(PDPATH)/src/s_main.o \
 $(PDPATH)/src/x_text.o \
 $(PDPATH)/src/x_connective.o \
 $(PDPATH)/src/x_arithmetic.o \
 $(PDPATH)/src/x_time.o \
 $(PDPATH)/src/g_canvas.o \
 $(PDPATH)/src/d_global.o \
 $(PDPATH)/src/m_obj.o \
 $(PDPATH)/src/g_io.o \
 $(PDPATH)/src/s_print.o \
 $(PDPATH)/src/g_editor.o \
 $(PDPATH)/src/d_ctl.o \
 $(PDPATH)/src/x_interface.o \
 $(PDPATH)/src/g_vdial.o \
 $(PDPATH)/src/g_guiconnect.o \
 $(PDPATH)/src/d_fft.o \
 $(PDPATH)/src/x_gui.o \
 $(PDPATH)/src/d_osc.o \
 $(PDPATH)/src/m_sched.o \
 $(PDPATH)/src/m_atom.o \
 $(PDPATH)/src/g_toggle.o \
 $(PDPATH)/src/d_soundfile.o \
 $(PDPATH)/src/g_readwrite.o \
 $(PDPATH)/src/g_graph.o \
 $(PDPATH)/src/g_vslider.o \
 $(PDPATH)/src/m_memory.o \
 $(PDPATH)/src/g_template.o\
 $(PDPATH)/src/m_pd.o \
 $(PDPATH)/src/g_clone.o \
 $(PDPATH)/src/x_vexp_if.o \
 $(PDPATH)/src/x_vexp.o \
 $(PDPATH)/src/x_vexp_fun.o \
 $(PDPATH)/src/x_midi.o \
 $(PDPATH)/src/s_midi.o \
 $(PDPATH)/src/s_midi_dummy.o \
 $(PDPATH)/src/s_audio_dummy.o \
